export const softwareDeliveryPages = [
  {
    id: "task_inbox",
    title: "Task Inbox",
    shortTitle: "Inbox",
    routeKey: "task-inbox",
    productStep: "task_inbox",
    artifactType: "task_inbox",
    artifactGroup: "requirement",
    producedArtifact: "Task selection context",
    viewLocation: "Current page + Evidence Drawer → Requirement",
    primaryQuestion: "现在要处理哪一个 PM 任务？",
    primaryAction: "Select Task",
    secondaryActions: ["Refresh Tasks", "Open Latest Task"],
    previousPage: null,
    nextPage: "pm_request",
    safetyLevel: "safe",
    description: "选择或进入一个 PM 需求，作为 Conduit Delivery Workbench 的起点。",
  },
  {
    id: "pm_request",
    title: "PM Request",
    shortTitle: "PM Request",
    routeKey: "pm-request",
    productStep: "pm_request",
    artifactType: "pm_request",
    artifactGroup: "requirement",
    producedArtifact: "PM original request",
    viewLocation: "Current page + Evidence Drawer → Requirement",
    primaryQuestion: "PM 的原始交付意图是什么？",
    primaryAction: "Submit PM Request",
    secondaryActions: ["Edit Request", "Preview Only"],
    previousPage: "task_inbox",
    nextPage: "requirement_brief",
    safetyLevel: "safe",
    description: "收集 PM 口语需求和 dry-run 选项，不暴露内部 backend stage。",
  },
  {
    id: "requirement_brief",
    title: "Requirement Brief",
    shortTitle: "Requirement",
    routeKey: "requirement",
    productStep: "requirement_brief",
    artifactType: "requirement_brief",
    artifactGroup: "requirement",
    producedArtifact: "Requirement DSL",
    viewLocation: "Current page + Evidence Drawer → Requirement",
    primaryQuestion: "这次需求是否已经足够清楚，可以进入分工？",
    primaryAction: "Approve Requirement Brief",
    secondaryActions: ["Ask Clarification", "Edit Brief"],
    previousPage: "pm_request",
    nextPage: "work_breakdown",
    safetyLevel: "review",
    description: "确认结构化需求、验收标准、Skill 匹配和未解决问题。",
  },
  {
    id: "work_breakdown",
    title: "Work Breakdown",
    shortTitle: "Breakdown",
    routeKey: "breakdown",
    productStep: "work_breakdown",
    artifactType: "work_breakdown",
    artifactGroup: "breakdown",
    producedArtifact: "Work Breakdown Document",
    viewLocation: "Current page + Evidence Drawer → Breakdown",
    primaryQuestion: "这次任务会改哪里？谁负责？怎么测？",
    primaryAction: "Approve Breakdown",
    secondaryActions: ["Edit Breakdown", "Regenerate Breakdown"],
    previousPage: "requirement_brief",
    nextPage: "implementation_plan",
    safetyLevel: "review",
    description: "确认 frontend/backend/data model/test/skill 分工。",
  },
  {
    id: "implementation_plan",
    title: "Implementation Plan",
    shortTitle: "Plan",
    routeKey: "plan",
    productStep: "implementation_plan",
    artifactType: "implementation_plan",
    artifactGroup: "plan",
    producedArtifact: "Implementation Plan",
    viewLocation: "Current page + Evidence Drawer → Plan",
    primaryQuestion: "实现顺序、目标文件和测试路径是否可执行？",
    primaryAction: "Approve Plan",
    secondaryActions: ["Edit Plan", "Regenerate Plan"],
    previousPage: "work_breakdown",
    nextPage: "code_changes",
    safetyLevel: "review",
    description: "确认模块级实现步骤和执行边界，再进入代码变更。",
  },
  {
    id: "code_changes",
    title: "Code Changes",
    shortTitle: "Code",
    routeKey: "code",
    productStep: "code_changes",
    artifactType: "code_diff",
    artifactGroup: "code",
    producedArtifact: "Changed files + diff summary",
    viewLocation: "Current page + Evidence Drawer → Code",
    primaryQuestion: "代码会产生哪些文件级变化？",
    primaryAction: "Open Diff Review",
    secondaryActions: ["Preview Changes", "Apply Changes"],
    previousPage: "implementation_plan",
    nextPage: "preview_effect",
    safetyLevel: "write-gated",
    description: "查看写入或预览产生的文件级变化，不直接触发远端动作。",
  },
  {
    id: "preview_effect",
    title: "Preview / Effect",
    shortTitle: "Preview",
    routeKey: "preview",
    productStep: "preview_effect",
    artifactType: "effect_preview",
    artifactGroup: "preview",
    producedArtifact: "Effect preview",
    viewLocation: "Current page + Evidence Drawer → Preview",
    primaryQuestion: "用户可见效果是否符合 PM 目标？",
    primaryAction: "Approve Effect Preview",
    secondaryActions: ["Open Local Preview", "Request UI Adjustment"],
    previousPage: "code_changes",
    nextPage: "verification",
    safetyLevel: "review",
    description: "用产品语言总结用户可见变化，为验证步骤提供上下文。",
  },
  {
    id: "verification",
    title: "Verification",
    shortTitle: "Tests",
    routeKey: "verification",
    productStep: "verification",
    artifactType: "test_result",
    artifactGroup: "tests",
    producedArtifact: "Test result",
    viewLocation: "Current page + Evidence Drawer → Tests",
    primaryQuestion: "测试证据是否足够支撑交付？",
    primaryAction: "Approve Verification",
    secondaryActions: ["Run Tests", "Inspect Failure"],
    previousPage: "preview_effect",
    nextPage: "review",
    safetyLevel: "test-gated",
    description: "查看测试命令、状态和失败位置，确认交付证据。",
  },
  {
    id: "review",
    title: "Audit Console",
    shortTitle: "Audit",
    routeKey: "audit",
    productStep: "review",
    artifactType: "review_report",
    artifactGroup: "review",
    producedArtifact: "Audit report",
    viewLocation: "Current page + Evidence Drawer → Audit",
    primaryQuestion: "交付前证据、风险、安全门禁和 readiness 是否可审计？",
    primaryAction: "Approve Audit",
    secondaryActions: ["Request Fix", "Open Evidence Ledger"],
    previousPage: "verification",
    nextPage: "delivery",
    safetyLevel: "review",
    description: "审计前序证据、风险登记和远端安全门禁，准备进入 Delivery 页面。",
  },
  {
    id: "delivery",
    title: "Delivery",
    shortTitle: "Delivery",
    routeKey: "delivery",
    productStep: "delivery",
    artifactType: "pr_readiness",
    artifactGroup: "pr",
    producedArtifact: "Local commit + PR readiness",
    viewLocation: "Current page + Evidence Drawer → PR",
    primaryQuestion: "是否已经准备好本地提交或远端 PR？",
    primaryAction: "Prepare Delivery",
    secondaryActions: ["Create Local Commit", "Generate PR Preview"],
    previousPage: "review",
    nextPage: null,
    safetyLevel: "remote-gated",
    description: "保留本地提交、远端 PR 预览和显式授权边界。",
  },
];
