const sharedForbiddenFiles = [
  "backend/**",
  "conduit-realworld-example-app/**",
  "backend/src/ai/agents/codeWriterAgent.js",
  "backend/src/ai/agents/testRunnerAgent.js",
  "backend/src/ai/delivery/prDeliveryAgent.js",
  ".env",
  "package-lock.json",
  "node_modules/**",
  "dist/**",
];

const pagePropsContract = "Receives { pageConfig, task, artifacts, currentArtifact, onNavigate, onRunStep, onRegenerate, onApprove, onRequestRevision, actions, loading, error } and renders only page-local UI.";

function createRole({
  id,
  name,
  responsibility,
  ownedFiles = [],
  allowedFiles = ownedFiles,
  forbiddenFiles = sharedForbiddenFiles,
  canEditApp = false,
  canEditBackend = false,
  canEditConduit = false,
  canEditDeliveryLogic = false,
  requiredInputs = [],
  outputContract = pagePropsContract,
  testScope = "frontend/src/App.test.jsx",
}) {
  return {
    id,
    name,
    responsibility,
    ownedFiles,
    allowedFiles,
    forbiddenFiles,
    canEditApp,
    canEditBackend,
    canEditConduit,
    canEditDeliveryLogic,
    requiredInputs,
    outputContract,
    testScope,
  };
}

export const pageTeamAssignments = [
  createRole({
    id: "flow_architect",
    name: "Flow Architect",
    responsibility: "Owns software delivery product-flow configuration and page metadata contract.",
    ownedFiles: [
      "frontend/src/productFlow/softwareDeliveryFlow.js",
      "frontend/src/productFlow/artifactGroups.js",
      "frontend/src/productFlow/stepNavigation.js",
    ],
    forbiddenFiles: [...sharedForbiddenFiles, "frontend/src/App.jsx"],
    requiredInputs: ["Product flow requirements", "artifact group mapping"],
    outputContract: "Stable softwareDeliveryPages, artifactGroups, and navigation helpers.",
    testScope: "software delivery product flow config tests",
  }),
  createRole({
    id: "flow_integrator",
    name: "Flow Integrator",
    responsibility: "Integrates page renderer and product-flow state into App.jsx without owning page internals.",
    ownedFiles: ["frontend/src/App.jsx", "frontend/src/pages/softwareDelivery/SoftwareDeliveryPageRenderer.jsx"],
    allowedFiles: [
      "frontend/src/App.jsx",
      "frontend/src/pages/softwareDelivery/SoftwareDeliveryPageRenderer.jsx",
      "frontend/src/pages/softwareDelivery/index.js",
      "frontend/src/productFlow/softwareDeliveryFlow.js",
      "frontend/src/productFlow/stepNavigation.js",
    ],
    canEditApp: true,
    requiredInputs: ["softwareDeliveryPages", "page component exports", "taskMode"],
    outputContract: "App-level renderer wiring only; no page-specific business logic.",
    testScope: "App default flow, renderer visibility, Labs fallback, Delivery/PR compatibility",
  }),
  createRole({
    id: "task_inbox_worker",
    name: "Task Inbox Worker",
    responsibility: "Owns Task Inbox page content and task selection UI skeleton.",
    ownedFiles: ["frontend/src/pages/softwareDelivery/TaskInboxPage.jsx"],
    forbiddenFiles: [...sharedForbiddenFiles, "frontend/src/App.jsx", "frontend/src/productFlow/softwareDeliveryFlow.js"],
    requiredInputs: ["pageConfig", "task list actions"],
  }),
  createRole({
    id: "pm_request_worker",
    name: "PM Request Worker",
    responsibility: "Owns PM Request page content and PM input experience.",
    ownedFiles: ["frontend/src/pages/softwareDelivery/PMRequestPage.jsx"],
    forbiddenFiles: [...sharedForbiddenFiles, "frontend/src/App.jsx", "frontend/src/productFlow/softwareDeliveryFlow.js"],
    requiredInputs: ["pageConfig", "requirement draft", "submit action"],
  }),
  createRole({
    id: "requirement_brief_worker",
    name: "Requirement Brief Worker",
    responsibility: "Owns Requirement Brief page and structured requirement review UI.",
    ownedFiles: ["frontend/src/pages/softwareDelivery/RequirementBriefPage.jsx"],
    forbiddenFiles: [...sharedForbiddenFiles, "frontend/src/App.jsx", "frontend/src/productFlow/softwareDeliveryFlow.js"],
    requiredInputs: ["pageConfig", "task.dsl", "requirement artifacts"],
  }),
  createRole({
    id: "work_breakdown_worker",
    name: "Work Breakdown Worker",
    responsibility: "Owns Work Breakdown page and work_breakdown artifact review UI.",
    ownedFiles: ["frontend/src/pages/softwareDelivery/WorkBreakdownPage.jsx"],
    forbiddenFiles: [...sharedForbiddenFiles, "frontend/src/App.jsx", "frontend/src/productFlow/softwareDeliveryFlow.js"],
    requiredInputs: ["pageConfig", "work_breakdown artifact", "task report"],
  }),
  createRole({
    id: "implementation_plan_worker",
    name: "Implementation Plan Worker",
    responsibility: "Owns Implementation Plan page and planning artifact review UI.",
    ownedFiles: ["frontend/src/pages/softwareDelivery/ImplementationPlanPage.jsx"],
    forbiddenFiles: [...sharedForbiddenFiles, "frontend/src/App.jsx", "frontend/src/productFlow/softwareDeliveryFlow.js"],
    requiredInputs: ["pageConfig", "solution plan", "module map"],
  }),
  createRole({
    id: "code_changes_worker",
    name: "Code Changes Worker",
    responsibility: "Owns Code Changes page and diff summary UI without changing writer behavior.",
    ownedFiles: ["frontend/src/pages/softwareDelivery/CodeChangesPage.jsx"],
    forbiddenFiles: [...sharedForbiddenFiles, "frontend/src/App.jsx", "frontend/src/productFlow/softwareDeliveryFlow.js"],
    canEditDeliveryLogic: false,
    requiredInputs: ["pageConfig", "changed files", "diff summary"],
  }),
  createRole({
    id: "preview_effect_worker",
    name: "Preview Effect Worker",
    responsibility: "Owns Preview / Effect page and product-effect summary UI.",
    ownedFiles: ["frontend/src/pages/softwareDelivery/PreviewEffectPage.jsx"],
    forbiddenFiles: [...sharedForbiddenFiles, "frontend/src/App.jsx", "frontend/src/productFlow/softwareDeliveryFlow.js"],
    requiredInputs: ["pageConfig", "effect preview artifact", "task report"],
  }),
  createRole({
    id: "verification_worker",
    name: "Verification Worker",
    responsibility: "Owns Verification page and test evidence UI without changing test runner behavior.",
    ownedFiles: ["frontend/src/pages/softwareDelivery/VerificationPage.jsx"],
    forbiddenFiles: [...sharedForbiddenFiles, "frontend/src/App.jsx", "frontend/src/productFlow/softwareDeliveryFlow.js"],
    requiredInputs: ["pageConfig", "test_result artifact", "test stage output"],
  }),
  createRole({
    id: "review_worker",
    name: "Review Worker",
    responsibility: "Owns Review page and safety/readiness review UI.",
    ownedFiles: ["frontend/src/pages/softwareDelivery/ReviewPage.jsx"],
    forbiddenFiles: [...sharedForbiddenFiles, "frontend/src/App.jsx", "frontend/src/productFlow/softwareDeliveryFlow.js"],
    requiredInputs: ["pageConfig", "review report", "safety gate"],
  }),
  createRole({
    id: "delivery_worker",
    name: "Delivery Worker",
    responsibility: "Owns Delivery page UI shell without changing real Delivery / PR behavior.",
    ownedFiles: ["frontend/src/pages/softwareDelivery/DeliveryPage.jsx"],
    forbiddenFiles: [...sharedForbiddenFiles, "frontend/src/App.jsx", "frontend/src/productFlow/softwareDeliveryFlow.js"],
    canEditDeliveryLogic: false,
    requiredInputs: ["pageConfig", "delivery state", "PR readiness"],
  }),
  createRole({
    id: "artifact_engineer",
    name: "Artifact Engineer",
    responsibility: "Owns shared artifact rendering components and artifact display contracts.",
    ownedFiles: ["frontend/src/components/artifacts/**"],
    forbiddenFiles: [...sharedForbiddenFiles, "frontend/src/App.jsx", "frontend/src/productFlow/softwareDeliveryFlow.js"],
    requiredInputs: ["artifactGroups", "artifact type contracts"],
    outputContract: "Reusable artifact display components only; no page ownership.",
    testScope: "artifact renderer component tests and App artifact regression tests",
  }),
  createRole({
    id: "qa_gatekeeper",
    name: "QA Gatekeeper",
    responsibility: "Performs read-only verification, regression triage, and safety checks.",
    ownedFiles: [],
    allowedFiles: [],
    forbiddenFiles: ["**/*"],
    requiredInputs: ["changed file list", "test commands", "acceptance criteria"],
    outputContract: "Read-only report with pass/fail evidence and risk notes.",
    testScope: "Runs requested tests only; does not directly edit code.",
  }),
];

export const writeLocks = {
  "frontend/src/App.jsx": {
    allowedRoleIds: ["flow_integrator"],
    rule: "Only Flow Integrator may modify App.jsx.",
  },
  "frontend/src/productFlow/softwareDeliveryFlow.js": {
    allowedRoleIds: ["flow_architect", "flow_integrator"],
    rule: "Only Flow Architect or Flow Integrator may modify product-flow configuration.",
  },
  "frontend/src/pages/softwareDelivery/TaskInboxPage.jsx": {
    allowedRoleIds: ["task_inbox_worker"],
    rule: "Only Task Inbox Worker may modify this page file.",
  },
  "frontend/src/pages/softwareDelivery/PMRequestPage.jsx": {
    allowedRoleIds: ["pm_request_worker"],
    rule: "Only PM Request Worker may modify this page file.",
  },
  "frontend/src/pages/softwareDelivery/RequirementBriefPage.jsx": {
    allowedRoleIds: ["requirement_brief_worker"],
    rule: "Only Requirement Brief Worker may modify this page file.",
  },
  "frontend/src/pages/softwareDelivery/WorkBreakdownPage.jsx": {
    allowedRoleIds: ["work_breakdown_worker"],
    rule: "Only Work Breakdown Worker may modify this page file.",
  },
  "frontend/src/pages/softwareDelivery/ImplementationPlanPage.jsx": {
    allowedRoleIds: ["implementation_plan_worker"],
    rule: "Only Implementation Plan Worker may modify this page file.",
  },
  "frontend/src/pages/softwareDelivery/CodeChangesPage.jsx": {
    allowedRoleIds: ["code_changes_worker"],
    rule: "Only Code Changes Worker may modify this page file.",
  },
  "frontend/src/pages/softwareDelivery/PreviewEffectPage.jsx": {
    allowedRoleIds: ["preview_effect_worker"],
    rule: "Only Preview Effect Worker may modify this page file.",
  },
  "frontend/src/pages/softwareDelivery/VerificationPage.jsx": {
    allowedRoleIds: ["verification_worker"],
    rule: "Only Verification Worker may modify this page file.",
  },
  "frontend/src/pages/softwareDelivery/ReviewPage.jsx": {
    allowedRoleIds: ["review_worker"],
    rule: "Only Review Worker may modify this page file.",
  },
  "frontend/src/pages/softwareDelivery/DeliveryPage.jsx": {
    allowedRoleIds: ["delivery_worker"],
    rule: "Only Delivery Worker may modify this page file.",
  },
  "frontend/src/components/artifacts/**": {
    allowedRoleIds: ["artifact_engineer"],
    rule: "Only Artifact Engineer may modify shared artifact rendering components.",
  },
  "backend/**": {
    allowedRoleIds: [],
    rule: "All frontend page team roles are forbidden from editing backend files in this workflow.",
  },
  "conduit-realworld-example-app/**": {
    allowedRoleIds: [],
    rule: "All teams are forbidden from editing Conduit unless separately authorized by the controller.",
  },
};
