const path = require("node:path");
const { loadSkills } = require("../skills/skillLoader");
const { loadProjectSkills } = require("../skills/projectSkillLoader");
const { SkillRegistry } = require("../skills/skillRegistry");
const { resolveSkillPlan } = require("../skills/skillPlanResolver");
const { buildRepositoryIndex } = require("../context/repositoryIndexer");
const { retrieveContext } = require("../context/retriever");
const { compileContextPackageFromDsl } = require("../context/graphify/contextPackageBuilder");
const { clarifyRequirement } = require("../agents/pmClarifierAgent");
const { createRequirementDslAsync } = require("../agents/requirementDslAgent");
const { deriveExecutionContract } = require("../dsl/v3/executionContract");
const { locateModules } = require("../agents/moduleLocatorAgent");
const { createSolutionPlan } = require("../agents/solutionPlannerAgent");
const { applyCodeChanges, previewCodeChanges } = require("../agents/codeWriterAgent");
const { runRealCodingAgent } = require("../agents/realCodingAgent");
const { runTestCommands } = require("../agents/testRunnerAgent");
const { createDeliveryReport } = require("../agents/deliveryReporterAgent");
const { createWorkBreakdownArtifact } = require("../agents/workBreakdownAgent");
const { writeChangeMemory } = require("../memory/changeMemoryStore");
const { runAlgorithmCompetitionPipeline } = require("./algorithmCompetitionPipeline");
const { TASK_MODES, normalizeTaskMode } = require("./taskModes");

function runPipeline({ requirement, taskMode, applyChanges = false, runTests = false, config }) {
  const normalizedTaskMode = normalizeTaskMode(taskMode);
  const taskId = createTaskId();
  const createdAt = new Date().toISOString();

  if (normalizedTaskMode === TASK_MODES.ALGORITHM_COMPETITION) {
    return runAlgorithmCompetitionPipeline({
      taskId,
      createdAt,
      requirement,
      applyChanges,
      runTests,
    });
  }

  throw new Error("Software delivery pipeline requires runPipelineAsync because RequirementDSL v3 is generated by a remote model.");
}

async function runPipelineAsync({ requirement, taskMode, applyChanges = false, runTests = false, config }) {
  const normalizedTaskMode = normalizeTaskMode(taskMode);
  const taskId = createTaskId();
  const createdAt = new Date().toISOString();

  if (normalizedTaskMode === TASK_MODES.ALGORITHM_COMPETITION) {
    return runAlgorithmCompetitionPipeline({
      taskId,
      createdAt,
      requirement,
      applyChanges,
      runTests,
    });
  }

  const skillsDirectory = path.join(__dirname, "../skills/definitions");
  const projectSkillsDirectory = path.join(__dirname, "../skills/project");
  const skills = loadSkills(skillsDirectory);
  const projectSkills = loadProjectSkills(projectSkillsDirectory);
  const registry = new SkillRegistry(skills);
  const matchedSkill = registry.match(requirement);
  const skillPlan = resolveSkillPlan({ requirement, legacySkill: matchedSkill, projectSkills });
  const stages = [];

  const clarification = clarifyRequirement(requirement, matchedSkill || skillPlan.primaryProjectSkill);
  stages.push(stage("pm-clarifier", clarification.status, clarification));

  const dslResult = await createRequirementDslAsync(requirement, {
    matchedSkill,
    skillPlan,
    missingQuestions: clarification.missingQuestions,
    clarifications: {},
  }, {
    ark: config.ark,
    chatCompletionImpl: config.chatCompletionImpl,
    promptAssets: config.dslPromptAssets,
  });
  stages.push(stage("requirement-dsl", dslResult.status, dslResult));

  if (dslResult.status === "failed" || dslResult.status === "needs_clarification") {
    return {
      id: taskId,
      createdAt,
      taskMode: normalizedTaskMode,
      requirement,
      applyChanges,
      runTests,
      status: dslResult.status,
      matchedSkill,
      projectMatchedSkill: skillPlan.primaryProjectSkill,
      skillPlan,
      dsl: dslResult.dsl,
      executionContract: null,
      stages,
      artifacts: [],
      report: null,
    };
  }

  const dsl = dslResult.dsl;
  const executionContract = deriveExecutionContract(dsl);

  const index = buildRepositoryIndex(config.conduitRepoPath);
  const retrievedContext = retrieveContext({
    query: requirement,
    index,
    contextHints: executionContract.contextHints,
    limit: 8,
  });
  stages.push(stage("context-rag", "completed", { filesIndexed: index.length, retrievedContext }));

  const graphifyContext = compileContextPackageFromDsl({
    finalDsl: executionContract,
    repoRoot: config.conduitRepoPath,
    graphifyRoot: config.graphifyRoot,
    options: { autoBuild: config.graphifyAutoBuild },
    keywordIndex: index,
    contextHints: executionContract.contextHints,
  });
  const moduleMap = locateModules({
    dsl: executionContract,
    retrievedContext,
    graphifyContextPackage: graphifyContext.contextPackage,
  });
  stages.push(stage("module-locator", "completed", moduleMap));

  const solutionPlan = createSolutionPlan({ dsl: executionContract, moduleMap });
  stages.push(stage("solution-planner", "completed", solutionPlan));

  const workBreakdownArtifact = createWorkBreakdownArtifact({
    requirement,
    dsl: executionContract,
    moduleMap,
    solutionPlan,
  });

  const writeResult = config?.codeAgentMode === "real" && applyChanges
    ? await runRealCodingAgent({
        repoRoot: config.conduitRepoPath,
        finalDsl: executionContract,
        solutionPlan,
        moduleMap,
        retrievedContext,
        graphifyContextPackage: graphifyContext.contextPackage,
        ark: config.ark,
      })
    : applyChanges
      ? applyCodeChanges({ repoRoot: config.conduitRepoPath, dsl: executionContract })
      : previewCodeChanges({ dsl: executionContract });
  stages.push(stage("code-writer", writeResult.status, writeResult));

  const testResult = runTestCommands({
    repoRoot: config.conduitRepoPath,
    commands: executionContract.testCommands,
    enabled: runTests && writeResult.status !== "failed",
  });
  stages.push(stage("test-runner", testResult.status, testResult));

  const report = createDeliveryReport({
    taskId,
    dsl: executionContract,
    moduleMap,
    solutionPlan,
    writeResult,
    testResult,
  });
  stages.push(stage("delivery-reporter", "completed", report));

  const memoryResult = writeChangeMemory({
    runDirectory: config.projectRoot ? path.join(config.projectRoot, ".ai-runs") : null,
    taskId,
    createdAt,
    requirement,
    dsl: executionContract,
    writeResult,
    testResult,
    report,
    skillPlan,
  });
  stages.push(stage("change-memory", memoryResult.status, memoryResult));

  return {
    id: taskId,
    createdAt,
    taskMode: normalizedTaskMode,
    requirement,
    applyChanges,
    runTests,
    status: writeResult.status === "failed" || testResult.status === "failed" ? "needs_fix" : "completed",
    matchedSkill,
    projectMatchedSkill: skillPlan.primaryProjectSkill,
    skillPlan,
    dsl,
    executionContract,
    stages,
    artifacts: [workBreakdownArtifact],
    report,
  };
}

function stage(name, status, output) {
  return {
    name,
    status,
    completedAt: new Date().toISOString(),
    output,
  };
}

function createTaskId() {
  return `task-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

module.exports = { runPipeline, runPipelineAsync };
